name: Upload Release Asset
on:
  workflow_dispatch:
  release:
    types: [ published ]

jobs:
  config:
    uses: ./.github/workflows/build_and_test.yml
    with:
      module: config
      module_id: anvillib-config
      mod_id: anvillib_config
      ci_build: false
      pr_build: false
    secrets:
      maven_url: ${{ secrets.MAVEN_URL }}
      maven_user: ${{ secrets.MAVEN_USER }}
      maven_pass: ${{ secrets.MAVEN_PASS }}

  integration:
    uses: ./.github/workflows/build_and_test.yml
    with:
      module: integration
      module_id: anvillib-integration
      mod_id: anvillib_integration
      ci_build: false
      pr_build: false
    secrets:
      maven_url: ${{ secrets.MAVEN_URL }}
      maven_user: ${{ secrets.MAVEN_USER }}
      maven_pass: ${{ secrets.MAVEN_PASS }}

  moveable-entity-block:
    uses: ./.github/workflows/build_and_test.yml
    with:
      module: moveable-entity-block
      module_id: anvillib-moveable-entity-block
      mod_id: anvillib_moveable_entity_block
      ci_build: false
      pr_build: false
    secrets:
      maven_url: ${{ secrets.MAVEN_URL }}
      maven_user: ${{ secrets.MAVEN_USER }}
      maven_pass: ${{ secrets.MAVEN_PASS }}

  recipe:
    needs:
      - config
    uses: ./.github/workflows/build_and_test.yml
    with:
      module: recipe
      module_id: anvillib-recipe
      mod_id: anvillib_recipe
      ci_build: false
      pr_build: false
    secrets:
      maven_url: ${{ secrets.MAVEN_URL }}
      maven_user: ${{ secrets.MAVEN_USER }}
      maven_pass: ${{ secrets.MAVEN_PASS }}

  main:
    needs:
      - config
      - integration
      - moveable-entity-block
      - recipe
    uses: ./.github/workflows/build_and_test.yml
    with:
      module: main
      module_id: anvillib
      mod_id: anvillib
      ci_build: false
      pr_build: false
    secrets:
      maven_url: ${{ secrets.MAVEN_URL }}
      maven_user: ${{ secrets.MAVEN_USER }}
      maven_pass: ${{ secrets.MAVEN_PASS }}